[package]
name = "stress-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.51"
futures = "0.3.19"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
