#!/bin/bash

set -e

remote="$1"
url="$2"

z40=0000000000000000000000000000000000000000

while read local_ref local_sha remote_ref remote_sha
do
  if [[ "${local_sha}" = $z40 ]]; then
    echo "Deleting stuff, nothing to do"
  else
    (
      set -x
      cd backend
      poetry install --no-root
      poetry run invoke lint
    )
  fi
done

exit 0
